KeYProject/key

.github/dlsmt.sh
.github/workflows/tests.yml

Currently, no SMT-solver is available during the CI build and test. 
This MR brings a small bash scripts, which download and "install" z3 and CVC5. Both SMT-solvers should be available via `$PATH`. Caching is activated. 
The script uses the `gh`, the cli application for/from Github, to download the latest releases.

Install SMT solvers for CI testing

---

key.util/src/main/java/org/key_project/util/helper/FindResources.java
key.util/src/main/java/org/key_project/util/lookup/Lookup.java

Java (as opposed to Groovy and Kotlin) does not support string templates of the form "$variable". Attempting to use the feature anyway results in a string which literally contains the text "$variable".
See JEP 430: https://openjdk.org/jeps/430

Fix use of unsupported string templates

---

key.ui/src/main/java/de/uka/ilkd/key/gui/LogView.java
key.ui/src/main/resources/logback.xml

Previously the filtering logic in LogView would fail to work properly if a log message contained a newline.

Fix handling of multiline log messages

---

key.core/src/main/java/de/uka/ilkd/key/java/PrettyPrinter.java
key.core/src/main/java/de/uka/ilkd/key/java/statement/JmlAssert.java
key.core/src/main/java/de/uka/ilkd/key/proof/io/IntermediateProofReplayer.java
key.ui/src/main/java/de/uka/ilkd/key/gui/ExampleChooser.java
key.ui/src/main/java/de/uka/ilkd/key/gui/SearchBar.java
key.ui/src/main/java/de/uka/ilkd/key/gui/fonticons/IconFactory.java
key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/SequentViewSearchBar.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIAbstractTreeNode.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIBranchNode.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIOneStepChildTreeNode.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeNode.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeSearchBar.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/Style.java
keyext.exploration/src/main/java/org/key_project/exploration/ExplorationExtension.java

I've digged these changes up from my main branch from over a year ago and made them cleaner.
* Cleanup some of the code
* Speed up ProofTreeSearchBar by caching the search strings (Makes a huge difference for large proofs)
* Fix example dialog loading previously hidden example on double-click on a folder
After: ![grafik](https://user-images.githubusercontent.com/23399687/216086358-e2badf5a-f3f6-424e-b867-eaba872f0470.png)
Before: ![grafik](https://user-images.githubusercontent.com/23399687/216086390-50dad39f-1c74-4300-bab2-d7b6f2c73fa4.png)
After: 
Before:

Proof tree view: Multiple small changes for readability

---

.git-blame-ignore-revs

After the git repository rewrite to remove a large file, the commit hashes changed. This PR fixes the commits listed in the `.git-blame-ignore-revs` file.

New .git-blame-ignore-revs after history rewrite

---

key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java

Steps to reproduce issue: try to instante a rule manually (e.g. cut). Observe that a NPE is thrown.
Caused by: #3012

Avoid tooltip NPE for incomplete proof nodes

---

key.core/src/main/java/de/uka/ilkd/key/settings/ProofIndependentSMTSettings.java
key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/proofcollection/TestFile.java

This fixes the recent `testRunAllFunProofs` failures. Without this fix, only `Z3_FP` is run when reloading a proof.

Activate Z3 if no other SMT solver is configured

---

key.core/src/main/java/de/uka/ilkd/key/java/KeYRecoderMapping.java

Fixes #1692. The null value is checked later on, leading to the construction of an exception with location information.

Report better error for missing model method

---

.github/workflows/code_quality.yml
.github/workflows/codeql.yml
.github/workflows/tests.yml

This PR adds the `merge_group` event as a trigger to the Github Action workflows. 
By adding this PR, we should be able to deploy the Merge Group (aka Merge Train) feature. Merge Group are the solution to allow to merge multiple PRs in one go, without updating them.

Add `merge_group` event to checks

---

key.ui/src/main/java/de/uka/ilkd/key/gui/settings/StandardUISettings.java

This is another style available by default.
EDIT: Code has been adapted as suggested by @wadoon.

Allow user to select any installed LaF

---

key.core/src/main/antlr4/JmlParser.g4
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/TextualTranslator.java
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
key.core/src/test/java/de/uka/ilkd/key/speclang/njml/NJmlTranslatorTests.java

Fixes #1722. Previously, the modifier was read after construction of `TextualJMLSpecCase`.

Register modifier when parsing JML spec

---

.github/workflows/tests.yml
recoder/src/test/java/recoder/testsuite/fixedbugs/FixedBugs.java

This PR enables the Java 17 for the `unit-tests` check in the Github workflow. 
A reflection test case in recoder's test suite is not compatible anymore, and was disabled. 
Impact on operation in KeY is unknown.

Enabling Java 17 for unit-tests

---

.github/workflows/artiweb.yml
.github/workflows/tests.yml

Uses a workaround described [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow) to hopefully create the comment for pull requests by remote repositories as well.

Better artiweb comment workflow

---

key.core/src/main/resources/de/uka/ilkd/key/java/JavaRedux/java/lang/Long.java

`Long.MIN_VALUE` and `Long.MAX_VALUE` should be of type `long` like it is in the JDK sources.
This change shouldn't impact any previously working proofs since these values get translated to the correct numbers in JavaDL as sort `int` regardless.
Theoretically this change could introduce new type issues when parsing previously working Java code, but this seems unlikely since the `int` types would probably have been widened to `long` before anyway.

Fix type of `Long.MIN_VALUE` and `Long.MAX_VALUE`

---

.github/workflows/nightlydeploy.yml

On Jenkins, we had a "nightly" build of KeY that was also deployed on the www11 sub-domain at the KIT. 
This PR adds a Github Action, which will update (delete and create) a release entry on the Github repo. This entry is marked as pre-release and contains a generated changelog. The current shadow-jar is attached. 
Example see here: https://github.com/KeYProject/key/releases/tag/nightly
This allows you to simple download the current version of KeY via `gh`:
```sh
$ gh release download nightly -R keyproject/key -p '*-exe.jar'
```
or by URL
```sh
wget https://github.com/KeYProject/key/releases/download/nightly/key-2.11.0-exe.jar
```
* Add further build artifacts? (Javadoc, ...)
/cc @mattulbrich @jwiesler @unp1

A Github Action for nightly deploy

---

.github/workflows/opttest.yml
.github/workflows/tests.yml

Optional tests are currently the tests of symbolic execution and proof references, required by KeY4clipse. 
**Before:** Optional tests were always executed on pushes on main and pull-requests.
**With this PR:** Optional tests are only executed every 10 days on the main branch or on manually demand.

Depromote optional-tests

---

key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InnerNodeView.java

If the new sequent has a different height than the previous view, repaint is called twice. To fix overlapping highlights, remove all highlights when painting the sequent.

Fix double highlight in sequent view

---

key.core/src/main/java/de/uka/ilkd/key/nparser/builder/AbstractBuilder.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/DefaultBuilder.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/ExpressionBuilder.java

the original code was not correct, threw NPEs and forgot the original cause exception.
* `e.getMessage()` could produce an NPE
* using `e.getMessage()` as format string was probably not the desired functionality here.
---
There is a second small bugfix related to error reporting: If an undefined schema variable is used as a bound variable, an NPE was thrown. This fix makes sure that "No schema variable x has been defined" is reported.

fixing error reporting in AbstractBuilder

---

key.core/src/main/java/de/uka/ilkd/key/java/ServiceCaches.java
key.core/src/main/java/de/uka/ilkd/key/strategy/feature/AbstractNonDuplicateAppFeature.java
key.core/src/main/java/de/uka/ilkd/key/strategy/feature/AppliedRuleAppsNameCache.java
key.core/src/main/java/de/uka/ilkd/key/strategy/feature/EqNonDuplicateAppFeature.java
key.core/src/main/java/de/uka/ilkd/key/strategy/feature/NonDuplicateAppFeature.java
key.core/src/main/java/de/uka/ilkd/key/strategy/feature/NonDuplicateAppModPositionFeature.java

I optimized the non duplicate app feature calculation by caching a map `rule name => [RuleApp]`.
This lead to an overall performance gain of about 20% for most cost computations done by the strategies.
I made some assumptions about `Node` that are not guaranteed by the interface (although I think they should be and `Node` could easily be made immutable).
See the doc of `getRuleAppsWithName`.
Two more things I noticed: 
* `NonDuplicateAppFeature::containsRuleApp` is always inverted
* Inverting the method to "does not contain" makes the code equal to `noDuplicateFindTaclet`, so I called this one instead
Is this really the case? `NonDuplicateAppFeature::filter` does a (now useless) case distinction over whether the position in occurrence is null and calls one of the two methods... It would …

Fix non duplicate feature perf

---

key.core/src/main/java/de/uka/ilkd/key/java/Recoder2KeY.java
key.core/src/test/java/de/uka/ilkd/key/speclang/njml/JMLParserExceptionTest.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/Bevhavioural.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/IllegalInv.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/README.md
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/TypeError.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/UnknownVar.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/UnknownVarInJML.java

JML parsing and error reporting is not yet ideal, we should fix these case.
They can also serve as valuable test cases for future replacement frameworks.
This also fixes a bug in the position treatement of Recoder2KeY.
From the javadoc:
This test case is used to ensure that errors in JML (and perhaps also in Java)
are reported with a reasonable error message and the right position pointing
into the file.
To add a test case, locate the "exceptional" directory in the resources
(below the directory for this package here) and add your single Java file
that contains an error that should be presented to the user (like syntax
error, unresolved names, ...)
The first lines of the Java file may contain meta data on what to expect
from the exception.
- introducing exceptional JML tests
- more test …

Test parsing exceptions in JML and Java parsing 

---

key.core.symbolic_execution/src/main/java/de/uka/ilkd/key/symbolic_execution/rule/ModalitySideProofRule.java
key.core/src/main/java/de/uka/ilkd/key/java/declaration/VariableSpecification.java
key.core/src/main/java/de/uka/ilkd/key/logic/Semisequent.java
key.core/src/main/java/de/uka/ilkd/key/logic/Sequent.java
key.core/src/main/java/de/uka/ilkd/key/proof/BuiltInRuleAppIndex.java
key.core/src/main/java/de/uka/ilkd/key/proof/Goal.java
key.core/src/main/java/de/uka/ilkd/key/proof/RuleAppIndex.java
key.core/src/main/java/de/uka/ilkd/key/proof/TacletAppIndex.java
key.core/src/main/java/de/uka/ilkd/key/proof/rulefilter/SetRuleFilter.java
key.core/src/main/java/de/uka/ilkd/key/prover/impl/PerfScope.java
key.core/src/main/java/de/uka/ilkd/key/strategy/QueueRuleApplicationManager.java
key.core/src/main/java/de/uka/ilkd/key/strategy/RuleAppContainer.java
key.core/src/test/resources/de/uka/ilkd/key/java/testAttachCommentsCompilationUnit_LockSpec.txt
key.core/tacletProofs/seqPerm2/Taclet_schiffl_lemma_2.proof
key.ui/examples/heap/permissions/lockspec/src/LockSpec.java
key.ui/src/main/resources/logback.xml

Make the rule app indices **lazy**, this speeds up all proof loading by at least 25% (the larger the proof the larger this number since the indices get slower). This is a refactoring needed to make enable further optimizations (skipping updates to the indices when not needed).

AutoPerf: Lazy rule indices

---

keyext.slicing/src/main/java/org/key_project/slicing/analysis/DependencyAnalyzer.java
keyext.slicing/src/test/java/org/key_project/slicing/EndToEndTests.java

This might fix #3176, we'll see..
Edit: testing on my machine creates a 30 KB `TEST-org.key_project.slicing.EndToEndTests.xml`.

Reduce logging in slicing extension

---

key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heap.key
key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heapRules.key

In JML, at the moment it is not possible to write down **as assertion** which heap locations (may) have been altered by the program up to the current location in code. The reason for this is that the sort Field is not available. The clause `assignable <locs>` in a method contract is encoded in JavaDL as follows:
```math
\begin{align}
\forall\ \text{Field}\ f. \forall\ \text{java.lang.Object}\ o&.\ (o,f) \in locs\\
&\vee o \neq \text{null} \wedge \neg o.< created>\ = TRUE\\
&\vee o.f@newHeap = o.f@oldHeap
\end{align}
```
This PR adds a predicate `assignable(Heap, Heap, LocSet)` that has a single taclet that rewrites it exactly into the above expression. The first parameter is the new heap, the second one the old heap. The taclet has a heuristic to be applied by automatic strategy after …

Make assignable predicate available in JML

---

key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowActiveSettingsAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/lemmatagenerator/LemmaSelectionDialog.java
key.ui/src/main/java/de/uka/ilkd/key/gui/lemmatagenerator/LoadUserTacletsDialog.java
key.ui/src/main/java/de/uka/ilkd/key/gui/settings/SettingsManager.java
key.ui/src/main/java/de/uka/ilkd/key/gui/smt/InformationWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/smt/ProgressDialog.java
key.ui/src/main/java/de/uka/ilkd/key/gui/utilities/StdDialog.java

This fixes the issue where some dialogs may appear in the wrong location if multiple displays are connected.

Set location of all dialogs relative to parent

---

key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/TaskTree.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/AbandonTaskAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowActiveTactletOptionsAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowKnownTypesAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowProofStatistics.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowUsedContractsAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/KeYGuiExtensionFacade.java

This PR adds a context menu to proof entries in the task tree. Entries are equal to the proof menu in the menu bar.

Add context menu to proofs in task tree

---

key.core/src/main/antlr4/KeYParser.g4
key.core/src/main/java/de/uka/ilkd/key/nparser/ParsingFacade.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/ExpressionBuilder.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java

This PR brings restructuring of the KeY's grammar `KeYParser.g4`  for more performance.
Some of the changes are critical as they change the grammar, and need to be discuss.
The **current situation** is as follows. All given benchmarks given on our biggest Key-file `javaRules.key`. *Parse time* should be treated carefully, as JIT and caching effects have critical. 
You see a lots of ambiguities and sometimes high maximal lookahead (max. 105).
The problem lies more in the *primitives* and some stupid rules. 
The following is possible, depending on the severity on changes. 
/cc @jwiesler @mattulbrich @unp1

Critical changes to the KeY parser/grammer for more performance

---

gradle/key_checks.xml
scripts/tools/checkstyle/key_checks.xml

There were two checkstyle files, not sure which is actually used so I changed both.

Checkstyle: ignore Javadoc warning on logger variables

---

key.ui/src/main/java/de/uka/ilkd/key/gui/InvariantConfigurator.java

When using a loop in a `.key` file without a Java source like this:
```java
\programVariables{
int i, n;
}
\problem {
n >= 0 & wellFormed(heap) ->
{ i:=0 } \[{
/*@ loop_invariant i <= n;
@ assignable \nothing; @*/
while (i < n) {
i = i + 1;
}
}\] (i = n)
}
```
using the loop invariant rule would result in a NullPointerException. This PR fixes this with an additional null check.

Fix InvariantConfigurator

---

key.ui/build.gradle
key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/KeyAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/docking/DockingLayout.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/api/KeYGuiExtension.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/KeYGuiExtensionFacade.java
key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/action_history/ActionHistoryExtension.java
key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/action_history/StateChangeListener.java
key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/action_history/UndoHistoryButton.java
keyext.action_history/build.gradle
keyext.action_history/src/main/resources/META-INF/services/de.uka.ilkd.key.gui.extension.api.KeYGuiExtension
keyext.exploration/src/main/java/org/key_project/exploration/ExplorationExtension.java
settings.gradle

View menu:
This reduces clutter in the main toolbar by:
- moving the action history next to the other undo buttons
- moving the layout controls to a menu (View -> Layout)
- marking the exploration extension as experimental (as documented)
- disabling the functionality to reorder toolbars (only ever used by accident)
As a bonus, the bug that extension panels sometimes fail to show up should also be fixed.

Reduce clutter in toolbar

---

.github/dlsmt.sh
.github/workflows/tests.yml
.github/workflows/tests_winmac.yml

The release tests had an error on non-linux environments s.t. `dlsmt.sh` breaks.
1. We fixed the shell to `bash` which repairs windows
2. We removed the shebang which fixes macos
Covert change: removal of `jacocoTestReport.xml` from the artifacts for unit-tests, which should decreases the huge size of `test-results`.

fixate bash as shell for dlsmt.sh

---

key.ui/src/main/java/de/uka/ilkd/key/gui/RecentFileMenu.java

We must ensure to create the "recentFiles" configuration file before passing the File object to an InputStream.

Fixes a NullPointerException when the configuration files for the "Recent Files" feature is not yet created

---

key.ui/src/main/java/de/uka/ilkd/key/gui/settings/StandardUISettings.java

When first started, KeY uses the Java cross-platform look-and-feel called Metal. But opening the settings dialog automatically selects the System look-and-feel as default.
Thus, when installing KeY on a platform that provides a system look-and-feel, you will see the Metal LnF at first, but as soon as you generate a settings file by opening the settings dialog, KeY will switch to the System LnF even if you don't select anything.
This PR fixes this by always applying Metal as the default.

Fix default look-and-feel in settings dialog

---

key.core/src/main/java/de/uka/ilkd/key/settings/ProofSettings.java

Generate configuration file 'proof-settings.prop' if none exists

---

key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/settings/FontSizeFacade.java
key.ui/src/main/java/de/uka/ilkd/key/gui/settings/StandardUISettings.java
key.ui/src/main/java/org/key_project/util/java/SwingUtil.java

Fixes #3234. The reason for the exceptions was a cycle in the main window construction (getInstance called in resizeFonts).
cc @WolframPfeifer

Fix infinite loop in MainWindow construction

---

recoder/build.gradle

One-liner fix: Update beanshell version in recoder's dependencies. 
The previous dependency version has a CVE.

Update BSH dependency of recoder

---

key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/FieldConstantHandler.java
key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/MasterHandler.java
key.core/src/test/java/de/uka/ilkd/key/smt/newsmt2/MasterHandlerTest.java
key.core/src/test/resources/de/uka/ilkd/key/smt/newsmt2/cases/heap2.props

Previously the fieldIdentifier symbol might never be introduced, leading to an exception when trying to run the SMT solver.
Fixes #3267

Fix dependency issue in SMT translation

---

key.core/src/main/antlr4/KeYParser.g4
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/ProblemFinder.java
key.core/src/main/java/de/uka/ilkd/key/proof/Proof.java
key.core/src/main/java/de/uka/ilkd/key/proof/init/KeYUserProblemFile.java
key.core/src/test/java/de/uka/ilkd/key/rule/CreateTacletForTests.java

On request, this PR changes the grammar of KeY files, s.t. problem statements can also be sequents. 
* Previous: ` problem: LBRACE term RBRACE;` 
* Now: ` problem: LBRACE termorseq RBRACE;`
This means, you are allow to write 
```
\problem {
a,b,c 
==> 
d, e, f
}
```
in KeY files.

Problem statements in KeY file can now also be a (semi-)sequent

---

build.gradle
key.core/build.gradle
key.core/src/main/java/de/uka/ilkd/key/control/KeYEnvironment.java
key.core/src/main/java/de/uka/ilkd/key/java/Services.java
key.core/src/main/java/de/uka/ilkd/key/logic/label/TermLabelManager.java
key.core/src/main/java/de/uka/ilkd/key/macros/ProofMacroFinishedInfo.java
key.core/src/main/java/de/uka/ilkd/key/macros/StrategyProofMacro.java
key.core/src/main/java/de/uka/ilkd/key/proof/Statistics.java
key.core/src/main/java/de/uka/ilkd/key/proof/reference/ReferenceSearcher.java
key.core/src/main/java/de/uka/ilkd/key/smt/communication/ExternalProcessLauncher.java
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/JmlChecks.java
key.core/src/test/java/de/uka/ilkd/key/proof/TestOneStepSimplifier.java
key.core/src/test/java/de/uka/ilkd/key/proof/replay/TestCopyingReplayer.java
key.core/src/test/java/de/uka/ilkd/key/speclang/njml/NJmlTranslatorTests.java
key.core/src/test/java/de/uka/ilkd/key/util/TestEqualsModProofIrrelevancy.java
key.ui/src/main/java/de/uka/ilkd/key/core/KeYMediator.java
key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/WindowUserInterfaceControl.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/AutoModeAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeModel.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreePopupFactory.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
keyext.slicing/src/main/java/org/key_project/slicing/analysis/DependencyAnalyzer.java

Changes:
- SMT solvers are properly terminated on timeout
- Proof Macro statistics are kept visible and only count the newly applied rules
- Stop button is disabled after use, re-enabled after stop completes (this is to avoid double activation)
- Bugfix: fully disable origin tracking if it is disabled
- Bugfix: proof slicing works even if a cut introduced no new formulas in any branch
- Bugfix: detection of active git branch always refreshes correctly
- Bugfix: when marking goal(s) as interactive/automatic, proof tree no longer loses expansion state

Misc. UI fixes

---

key.core/build.gradle
key.core/src/main/resources/de/uka/ilkd/key/smt/solvertypes/Z3_QF.props

This PR adds a variant of the Z3 SMT configuration which excludes quantifiers, making it much faster for certain problems. I will update this PR with my usecase if I can find it again.
Additionally the PR enhances the gradle task definitions by specifying inputs and outputs, which allows gradle to automatically respond to new .props files.

SMT: add Z3_QF variant

---

build.gradle
key.core/build.gradle
key.core/src/main/java/de/uka/ilkd/key/control/KeYEnvironment.java
key.core/src/main/java/de/uka/ilkd/key/java/Services.java
key.core/src/main/java/de/uka/ilkd/key/logic/label/TermLabelManager.java
key.core/src/main/java/de/uka/ilkd/key/macros/ProofMacroFinishedInfo.java
key.core/src/main/java/de/uka/ilkd/key/macros/StrategyProofMacro.java
key.core/src/main/java/de/uka/ilkd/key/proof/Statistics.java
key.core/src/main/java/de/uka/ilkd/key/proof/reference/ReferenceSearcher.java
key.core/src/main/java/de/uka/ilkd/key/smt/communication/ExternalProcessLauncher.java
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/JmlChecks.java
key.core/src/main/java/de/uka/ilkd/key/util/MiscTools.java
key.core/src/test/java/de/uka/ilkd/key/proof/TestOneStepSimplifier.java
key.core/src/test/java/de/uka/ilkd/key/proof/replay/TestCopyingReplayer.java
key.core/src/test/java/de/uka/ilkd/key/speclang/njml/NJmlTranslatorTests.java
key.core/src/test/java/de/uka/ilkd/key/util/TestEqualsModProofIrrelevancy.java
key.ui/src/main/java/de/uka/ilkd/key/core/KeYMediator.java
key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/WindowUserInterfaceControl.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/AutoModeAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeModel.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreePopupFactory.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
keyext.slicing/src/main/java/org/key_project/slicing/analysis/DependencyAnalyzer.java

Backporting the bug fixes in KEY-2.12.1 to main. This PR supersedes #3251 to avoid merge conflicts due to file header changes. Necessary changes were cherry-picked.

Backport of KEY-2.12.1 into main

---

key.ui/src/main/java/de/uka/ilkd/key/gui/actions/QuickSaveAction.java

Quicsave always displayed a failed warning, een in success cases.wq

Fix wrong quicksave failed warning

---

key.core/src/main/java/de/uka/ilkd/key/logic/LabeledTermImpl.java
key.core/src/main/java/de/uka/ilkd/key/logic/TermFactory.java
key.core/src/main/java/de/uka/ilkd/key/logic/TermImpl.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/AbstractSort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/ArraySort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/GenericSort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/ProgramSVSort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/ProxySort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/Sort.java
key.core/src/main/java/de/uka/ilkd/key/logic/sort/SortImpl.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/DeclarationBuilder.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/ExpressionBuilder.java
key.core/src/main/java/de/uka/ilkd/key/rule/inst/SVInstantiations.java
key.core/src/main/java/de/uka/ilkd/key/taclettranslation/lemma/GenericRemovingLemmaGenerator.java
key.core/src/main/java/de/uka/ilkd/key/taclettranslation/lemma/UserDefinedSymbols.java

This PR makes TermImpl package private again (no entity outside of de....logic should see an actual implementation).
Further the PR strengthens the design decision of terms and sorts being immutable by making fields final and eliminating
setters.

Restore TermImpl to package private and strengthen immutability of term and sorts

---

key.core/src/main/resources/META-INF/services/de.uka.ilkd.key.proof.init.DefaultProfileResolver
key.ui/src/main/java/de/uka/ilkd/key/core/Main.java
key.ui/src/main/java/de/uka/ilkd/key/gui/utilities/HeapStatusExt.java
key.ui/src/main/resources/META-INF/services/de.uka.ilkd.key.gui.extension.api.KeYGuiExtension

This PR brings two things for a clear indication of the current heap size settings. 
1. The logging level for heap information is increased from debug to info in `Main#main()`.
Now the line 
```
[14:33:40.367] INFO  Main - Memory: total 250.0 MB, max 3948.0 MB, free 236.08212280273438 MB
```
should always appear. 
2. A GUI extension for the status bar: 
which allows to trigger `System.gc()` and to start the `jconsole` monitoring tool.

A heap indicator in KeY's status bar

---

.github/workflows/code_quality.yml
.github/workflows/gradle-publish.yml
.github/workflows/javadoc.yml
.github/workflows/opttest.yml
.github/workflows/tests.yml
.github/workflows/tests_winmac.yml
.github/workflows/update_symbex_oracles.yml

This PR enables the newest LTS version of Java in Githubs CI. 
:warning: This does not increase the `--release` or language level for KeY. New features are not enabled. 
:exclamation: Java 21 still not available for Github Actions.

Update to Java 21 Runtime for Testing

---

key.ui/src/main/java/de/uka/ilkd/key/gui/IssueDialog.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/KeYProjectHomepageAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/ExtensionManager.java
key.ui/src/main/java/de/uka/ilkd/key/gui/help/HelpFacade.java
key.ui/src/main/java/de/uka/ilkd/key/gui/help/HelpInfo.java
key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/caching/CachingExtension.java
key.ui/src/main/java/de/uka/ilkd/key/gui/settings/SimpleSettingsPanel.java
key.ui/src/main/java/org/key_project/util/java/SwingUtil.java
keyext.exploration/src/main/java/org/key_project/exploration/ExplorationExtension.java
keyext.proofmanagement/src/main/java/org/key_project/proofmanagement/ProofManagementExt.java
keyext.slicing/src/main/java/org/key_project/slicing/SlicingExtension.java

Purpose of this PR: make it easier to find the KeY docs. The help buttons seen below lead to the docs / the extension's readme.
TODO: write a one-line description for each extension
Other changes:
- fixed the `BROWSE` action on Linux (see `SwingUtil`)

Add help buttons to extension settings

---

key.core/src/main/java/de/uka/ilkd/key/proof/init/KeYUserProblemFile.java
key.core/src/main/java/de/uka/ilkd/key/proof/mgt/RuleJustificationInfo.java
key.core/src/main/resources/de/uka/ilkd/key/proof/rules/wdNumericalRules.key

Taclet names must be unique (per rule option). The corresponding check was commented out. 
This PR reenables the check and removes to duplicate taclets (identical taclets with equal names)

Re-enable check for non-unique taclet names and remove two taclet duplicates

---

key.core/src/main/java/de/uka/ilkd/key/settings/ViewSettings.java
key.ui/src/main/java/de/uka/ilkd/key/core/KeYSelectionModel.java
key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/HidePackagePrefixToggleAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/PrettyPrintToggleAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/SyntaxHighlightingToggleAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/UnicodeToggleAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIBranchNode.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeModel.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreePopupFactory.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeSearchBar.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
key.ui/src/main/java/de/uka/ilkd/key/proof/io/ProblemLoader.java

This pull request addresses #3367
Activating a filter works immediately. 
The underlying problem is that the GUIProofTreeModel stores the selection and does not update with the selection model in the ProofTreeView.
This PR does not maintain the consistency. The redundant information was seemingly only thought to be used to store the selected node when switching proofs and restoring it when switching back. The method setFilter should for that reason not query the model for the selection but the view to get an up-to-date path.
Previously it got null (despite a node being selected in the view) and  did not activate the filter.

Fix update of proof tree in case of filter changes (fixes #3367)

---

key.core/src/main/java/de/uka/ilkd/key/settings/GeneralSettings.java
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/JmlMarkerDecision.java

This PR allows you to configure the *enabled keys* in the processing of the JML conditions within the *JML conditional annotation texts*. Currently, the set is hard coded and only contains `key` as the only enabled key. This means, that KeY accepts the following JML annotation texts:
* `/*@ ...*/`
* `/*+key@ ...*/`
* `/*+key+openjml@ ...*/`
but ignores
* `/*+openjml@ ...*/`
* `/*-key@ ...*/`
* This PR adds a new field to the `GeneralSettings` which contains a set of enabled keys.
* You can set this field either by `-PJML_ENABLED_KEYS=a,b,c` on the CLI, or 
* via the `$HOME/.key/proofIndependentSettings.json`.
Currently, there is no GUI element to configure this element. 
**The need** for this raises from case study where you want to have the same source code as the foundation, but you …

Configurable enabled keys for JML condition evaluation

---

key.core/src/main/java/de/uka/ilkd/key/settings/ProofIndependentSettings.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/ExtensionSettings.java
key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/KeYGuiExtensionFacade.java

This changes the display of extension-provided context menu actions. If they set a menu path, it will now be respected when constructing the popup menu.
The second commit fixes a bug where it was no longer possible to disable extensions (they would always re-enable on next KeY launch).

Always sort extension actions in context submenus (+bugfix to allow disabling extensions)

---

README.md

We require Java 17 now. Probably it is a good idea to update that before the HacKeYthon.

Update README.md (license date and Java version)

---

key.core/src/main/java/de/uka/ilkd/key/speclang/njml/OverloadedOperatorHandler.java
key.core/src/test/java/de/uka/ilkd/key/speclang/jml/TestJMLTranslator.java

Activate the operator overloading handler for the Sequence datatype. 
@mattulbrich The last change is from you on the particular line. 
- **X** Bug fix (non-breaking change which fixes an issue)
- **not really** New feature (non-breaking change which adds functionality)
- **X** There are changes to the (Java) code
- **X** I have tested the feature as follows: Test file
```
class SeqTest {
/*@ ensures \seq(1,2,3) == \seq(1) + \seq(2,3);*/
void foo() {}
}
```

Activate the OverloadedOperatorHandler.java for Sequence datatype

---

key.core/src/main/java/de/uka/ilkd/key/java/recoderext/JMLTransformer.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/IllegalInv.java

Solved an issue with row/column numbers caused by the comment concatenation. The issue occurred when there was code (class declaration) between two comments parented to the class.

Solved an issue with row/column numbers in JML Parser

---

key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/TypeError.java

This PR fixes the position info of the error for incorrect equality expressions.

Fix position info for equality expr errors

---

key.core/src/main/java/de/uka/ilkd/key/settings/GeneralSettings.java
key.ui/build.gradle
key.ui/src/main/java/de/uka/ilkd/key/gui/JmlEnabledKeysIndicator.java
key.ui/src/main/java/de/uka/ilkd/key/gui/MainStatusLine.java
key.ui/src/main/resources/META-INF/services/de.uka.ilkd.key.gui.extension.api.KeYGuiExtension

Addition to #3373 which brings the following UI element: 
A label which represents the current value of the enabled keys in `GeneralSettings`.

JML enabled keys indicator for the Status Line 

---

key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ShowProofStatistics.java

This pull request addresses #1533 .
This replaces the fix seperator "," with a static final String which may be set arbitrarily. This resolved the described problems in the description of the issue.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] There are changes to the (Java) code
- [ x ] I made sure that introduced/changed code is well documented (javadoc and inline comments).
- [ x ] I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- [ x ] I have tested the feature as follows: Saved CSV-statistics and loaded it. Saved proof files and loaded them. 
- [ x ] I have checked that runtime performance has not deteriorated.
The contributions within this pull request are licensed under GPLv2 (only) for inclusion in …

fixes #1533

---

key.ui/src/main/java/de/uka/ilkd/key/gui/ExampleChooser.java

Added a checkbox to the example loader dialog that allows to hide it on subsequent startups. I consider this a reasonable change as this functionality is already supported by KeY but hidden in the preferences which most user might never open. Additionally i think this is standard behavior for similar IDEs or programs. No default behavior is changed.

added checkbox to disable example loader directly in dialog

---

key.core/src/main/java/de/uka/ilkd/key/nparser/ParsingFacade.java
key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettings.java
key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettingsProvider.java

This pull request fixes #3416.
This PR removes the fallback to the old `.properties` file in ColorSettings.
Due to an issue in static initialization order, it is not possible to use the SettingsManager to (attempt to) read the old configuration file.

Fix startup crash if ~/.key/colors.json is not present

---

.github/dlsmt.sh

Fix the downloading of SMT solver in the CI pipeline. 
Version of z3 and CVC5 are now pinned.

fix smt solver downloader script

---

key.core/src/main/java/de/uka/ilkd/key/nparser/ParsingFacade.java
key.core/src/main/java/de/uka/ilkd/key/util/ExceptionTools.java
key.core/src/test/java/de/uka/ilkd/key/util/ExceptionToolsTest.java
key.core/src/test/resources/testcase/parserErrorTest/missing_semicolon.key
key.ui/src/main/java/de/uka/ilkd/key/gui/IssueDialog.java

#3406 leads to user-facing ParseCancellationExceptions, which are not debuggable. This PR enhances the user experience by actually showing the error in the context of the input file, and listing the found token and the expected token types. Previously, only the class name of the exception was displayed.
`missing_semicolon.key`
```
\rules {
missingSemicolon {
\find(0=0)
\replacewith(1=1)
}
}
\problem { 0=0 }
```

Nicer error message for parse errors

---

key.core/src/main/java/de/uka/ilkd/key/proof/init/DependencyContractPO.java

This pull request fixes #3411.
KeY will report an exception when the user attempts to open a proof obligation for void methods.

Prevent Dependency PO generation for void methods

---

key.core/src/main/antlr4/JmlParser.g4
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java

- Support of `\array2seq` and `\seq_put` (and `\seq_upd`) in JML
(Currently hard coded. It could be better if we add meta-data to functions or have theories)
- Fix `\locset(x.*,a[*])`, merge with \storeref function
Tested with the current of the FM tutorial.

Add key features for the FM tutorial

---

key.core/src/main/antlr4/JmlParser.g4
key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
key.core/src/test/java/de/uka/ilkd/key/speclang/njml/ExpressionTranslatorTest.java
key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exprs.txt

Currently, \seq() and \locset() are syntactically illegal, but should represent the empty set and empty sequence resp.
- New feature (non-breaking change which adds functionality)
- I added new test case(s) for new functionality.

Allow "\seq()" and "\locset()" in JML

---

key.core/src/main/java/de/uka/ilkd/key/taclettranslation/lemma/EmptyEnvInput.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/LemmaGenerationAction.java

* This commit fixes an NPE when loading
* This commit fixes missing or inconsistent selection of loaded proof
obligation
This pull request addresses #3477.
Fix the NullPointerException when loading a taclet proof obligation.
In addition the PO selection was inconsistent, which is fixed as well.
- I have tested the feature as follows: Loaded Taclet POs (both a single one as well as several at once)

Fix loading of taclet proof obligations (issue #3477)

---

key.core/src/main/java/de/uka/ilkd/key/macros/scripts/RuleCommand.java

Rules in script could not be applied if there were free logical variable schema variables around.
This is the case for class invariant rules and others.
The commit fixes the issue by copying code from how it is done for interactive rule applications.
More rules can be applied.
- I have tested the feature as follows: FM case study

RuleCommand can now deal with rules that have schema variables for logical variables

---

key.core/src/main/resources/de/uka/ilkd/key/proof/rules/integerAssignment2UpdateRules.key
key.core/src/test/java/de/uka/ilkd/key/rule/IntSemanticsTest.java
key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/IntSemanticsCheckedOF.java
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/mOFCheck.proof
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/mOFCheckWrong.key
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/IntSemanticsJava.java
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/intSemanticsJava.key
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/mJava.proof
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/mJavaWrong.key
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/IntSemanticsUncheckedOF.java
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/intSemanticsUncheckedOF.key
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/mBigint.proof
key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/mBigintWrong.key

The recently merged PR #3353 only partially fixes the overflow checking: All the taclets in `integerAssignment2UpdateRules.key`, which add another formula to the sequent for the overflow check, are missing the `\sameUpdateLevel` constraint. This can lead to unprovable overflow check branches (see the `inInt` line in the screenshot below, which talks about the variables `_a` and `_b` instead of `a` and `b`).
Btw.: I think that the bug is "only" a completeness issue and not soundness critical, since the variables can only appear in the inInt(...) predicate and the original modality and nowhere else on the sequent.
In addition to the fix in the rules, this PR adds test cases (one provable and one unprovable) for each of the test cases, which hopefully will help in the future to detect such …

Overflow follow up fix

---

key.core/src/main/java/de/uka/ilkd/key/proof/io/OutputStreamProofSaver.java
key.core/src/test/java/de/uka/ilkd/key/proof/io/ProofSaverTest.java

Parsing sequents in \problem{...} has been supported for a while now. This commit adapts the saving routine accordingly.
This is unintentionally reported in #3483.
There the actual problem here is shadowed by this problem here.
Currently sequents can be formulated in the `\problem` section, but cannot be stored.
This fix changes that.
- New feature (non-breaking change which adds functionality)
- I added new test case(s) for new functionality.

saving proofs for sequent problems

---

key.ui/src/main/java/de/uka/ilkd/key/gui/WindowUserInterfaceControl.java

Removes the explicit ctrl+c handling in `WindowsUserInterfaceControl`
See bug report: #3456.

Remove Ctrl+C handling, see #3456

---

key.core/src/main/java/de/uka/ilkd/key/speclang/LoopSpecImpl.java
key.core/src/main/java/de/uka/ilkd/key/speclang/LoopSpecification.java
key.ui/src/main/java/de/uka/ilkd/key/gui/InvariantConfigurator.java

This PR fixes a bug that prevented the interactive provision of a loop invariant.
It should be possible to enter loop invariants manually.
The problem was if no "free modifies"/"free assignable" was available then creating the whole modifies set  "union(freeMod, mod)" led to a NullPointerException. The fix uses "strictly_nothing" as default for free assignables of loops, if non given.

Fix for the LoopInvariantConfigurationDialog

---

key.util/build.gradle
key.util/src/main/java/org/key_project/util/collection/DefaultImmutableMap.java
key.util/src/main/java/org/key_project/util/collection/ImmutableArray.java
key.util/src/main/java/org/key_project/util/collection/ImmutableMap.java
key.util/src/main/java/org/key_project/util/collection/ImmutableMapEntry.java
key.util/src/main/java/org/key_project/util/collection/ImmutableSLList.java
key.util/src/main/java/org/key_project/util/collection/Immutables.java
key.util/src/test/java/org/key_project/util/collection/DefaultImmutableMapTest.java
key.util/src/test/java/org/key_project/util/testcase/collection/TestMapAsListFromIntegerToString.java

For a while the checker framework raised an exception during CI. This adds type annotations to remove the errors-
No more failing CI.
I refactored the util classes a bit, but there should be no different behaviour.
- Refactoring (behaviour should not change change)
- I added new test case(s) for new functionality / existing functionality
See https://eisop.github.io/cf/manual/manual.html#map-key-defaults-lowerbound for details on the fix.
Thanks to @wmdietl  and @flo2702 for fixing this with me.

Repairing the NonNull checker framework exception

---

key.core/src/main/java/de/uka/ilkd/key/util/KeYConstants.java

Changes the copyright notice in the "about" dialog to read "2001 – 2024" instead of "2023"

Fix copyright notice

---

key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettingsProvider.java

This PR fixes a visual bug in the Options dialog when changing the colors.
The bug was originally discovered by @BookWood7th (on Windows, but I think that is irrelevant), who also provided this screenshot that shows the problem:
* Fix of the visual bug where during editing of a color text field, the text gets unreadable and weirdly overlaps. The fix was to set the field to transparent. I do not know why it works, but somehow opaque components do not work correctly with background colors that also contain alpha.
* Fix: For the preview icons besides the color (in non-edited cells), the alpha channel was not correctly interpreted: It seems that it was interpreted as if the background was black. When merged with the non-alpha part, it resulted in colors that are usually not shown in the GUI …

Fix for visual bug with overlapping/unreadable text in color settings

---

key.core/src/main/java/de/uka/ilkd/key/settings/ViewSettings.java
key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
key.ui/src/main/java/de/uka/ilkd/key/gui/actions/ToggleProofTreeTooltipAction.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeSettingsMenuFactory.java
key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java

Trying to solve #3500, this PR does two things:
* It adds an option to disable the ProofTree tooltips, as requested for example by @unp1 and @mattulbrich. This option can be set in the options of the proof tree (gear icon) as well as in the global menu via "View" -> "Show ProofTree Tooltips" (where the SequentView and SourceView tooltips also can be toggled).
* A tooltip is now lazily rendered directly when it is needed, not already during creation of the GUITreeNode.
This pull request addresses #3500.
- Breaking change (fix or feature that would cause existing functionality to change)
- There are changes to the taclet rule base
- There are changes to the deployment/CI infrastructure (gradle, github, ...)
- Other: 
- I …

Option to disable ProofTree tooltips, render them lazily

---

build.gradle

In the KaKeY meeting (2024-10-25), we discussed a change of the version scheme. To be more precise, we want to drop the old Linux kernel/odd-even version numbering. 
*Currently,* the development version of KeY is 2.13.0. The release created from this development will be `2.14.0`. After this release, the development version will become `2.15.0`. Odd numbers for development, even numbers for releases.
**New,** we keep in line with our release versioning. The current released version is `2.12.3`, so our development version would be `2.12.4-dev`. If the version steps through the releasing stages, it becomes `2.12.4-alpha`, `2.12.4-beta`, and `2.12.4-rc`. Finally, it will result in the release `2.12.4`. If the release is larger, it can also be lifted from PATCH to MINOR and become the release …

Using semantic version (SemVer) scheme for KeY

---

key.core/src/main/resources/de/uka/ilkd/key/proof/rules/floatRulesAssumeStrictfp.key

It seems that there are two rules missing which convert from javaUnaryMinusFloat/Double to negFloat/negDouble. Without these rules, KeY (and also the SMT float conversion) can not prove very much when a negation occurs, since the function will just be left uninterpreted.
This PR just adds the two missing rules.
Caveat: Somebody with more knowledge about floating points should double-check this PR (I think it should be sound but am not 100% sure).
-[x] Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
-[x] There are changes to the taclet …

Add conversion rules for Float/Double negation

---

key.core/src/main/java/de/uka/ilkd/key/parser/Location.java

This pull request addresses #3518.
Adds explicit nullsLast comparators using the natural order of URI and Position when comparing locations.
This avoids a NullPointerException, when fileUri field is null in one of the locations being compared
- I have tested the feature as follows: KeY test suite

fixes Location#compareTo(Location)

---

key.core/src/main/java/de/uka/ilkd/key/proof/Goal.java
key.core/src/main/java/de/uka/ilkd/key/rule/AbstractExternalSolverRuleApp.java
key.core/src/main/java/de/uka/ilkd/key/smt/SMTRuleApp.java

#3514
Currently goals are only closed if the associated taclet is a closing taclet or alternatively if the rule application is a SMTRuleApp.
To enable other external solvers to close goals, this pull request adds a layer of abstraction that is used instead of SMTRuleApp to determine if the goal was closed.
- I have tested the feature as follows: KeY test suite
- I have checked that runtime performance has not deteriorated.

RuleApp interface for all external solvers (prep for #3514)

---

key.ui/src/main/java/de/uka/ilkd/key/ui/ConsoleUserInterfaceControl.java

The auto-mode in KeY does no longer work: It merely loads a file but does not try to prove it.
This PR partially reverts changes introduced in 8b6df72e14ac9ed620961d93db0a779fc65b7a6a.
- I have tested the feature as follows: Run it on the CLI
It re-establishes CLI behaviour that we used to have in KeY.

Fixing the broken automode

---

key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java

This pull request addresses #3427, but does not solve it.
The axiom taclet created for adt was not applicable. It is applicable now.
- I have tested the feature as follows: Looked at the translation of a few examples
It is a small change in the creation of a taclet.

repair the axiom generation for adts defined in JavaDL

---

key.ui/src/main/java/de/uka/ilkd/key/gui/smt/InformationWindow.java

…lignment
This pull request addresses #3557.
This changes the font size of the line numbering in the information window of the SMT translation interface.
- I have tested the feature as follows: KeY test suite and checking alignment for different font settings
- I have checked that runtime performance has not deteriorated.

Fix line number alignment in SMT interface

---

key.core/src/main/resources/de/uka/ilkd/key/proof/rules/soundDefaultContracts.key
key.ui/src/main/resources/de/uka/ilkd/key/gui/help/choiceExplanations.xml

Adds documentation for the taclet option added by [#3431](https://github.com/KeYProject/key/pull/3431).

Add documentation for soundDefaultContracts feature

---

key.core/src/main/antlr4/KeYLexer.g4

This pull request includes a change to the `IMPLICIT_IDENT` rule in the `KeYLexer.g4` file to allow an optional dollar sign before the letter sequence.
Lexer rule modification:
* [`key.core/src/main/antlr4/KeYLexer.g4`](diffhunk://#diff-6bd99bd35a45e33957236412344cc2b131e25b91957c7287bbaa5d0ecfa5a56cL391-R391): Modified the `IMPLICIT_IDENT` rule to accept an optional dollar sign ('<) before the letter sequence.
The reason is that static invariants are represented as `Classname::<$inv>` which one was not able to use in a manual cut.
But valid key terms should be parseable.
It is only a 4 character fix allowing implicit identifiers to start with a `$`.
- Bug fix (non-breaking tiny change which fixes an issue)
n/a
The contributions within this pull request are licensed under GPLv2 (only) for …

fixing lexing to support static invariants

---

key.core/src/main/resources/de/uka/ilkd/key/smt/solvertypes/CVC4.props
key.core/src/main/resources/de/uka/ilkd/key/smt/solvertypes/CVC4_legacy.props
key.core/src/main/resources/de/uka/ilkd/key/smt/solvertypes/CVC5.props

This small fix removes the delimiters in CVC4.props and also sets CVC4 and also cvc5 to `--no-interactive`, which fixes the (at least most?) crashes with the `Stream closed` error message.

Fixed obtaining results from CVC4 and cvc5

---

key.core/src/main/java/de/uka/ilkd/key/smt/communication/CVC5Socket.java
key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/ModularSMTLib2Translator.java
key.core/src/main/resources/de/uka/ilkd/key/smt/solvertypes/CVC5.props

CVC5 now also supports printing unsat cores, https://github.com/cvc5/cvc5/pull/9353 has been released for years.
Enable "Focus goals" function for CVC5.
- New feature (non-breaking change which adds functionality)
- Other: changes to the SMT properties

Enable SMT focus goals (unsat cores) for CVC5

---

key.core/src/test/java/de/uka/ilkd/key/util/TestMiscTools.java

Fixes the wrong test case `testMakeFilenameRelativeWindows`. 
The path `/home/daniel/` is valid on Windows, but the old implementation failed.

fix testMakeFilenameRelativeWindows

---

.github/pull_request_template.md
.github/workflows/tests.yml

None
Small change to the GitHub workflow for unit testing. Now, the test matrix is also over each individual module. Therefore, each module is tested separately. 
* Easier to spot individual failing modules
* More things in parallel lead to faster failures
* Fine-grained download of individual reports for each module. 
* Higher CPU usage: KeY is compiled more often 
(Note: artefact sharing between jobs (upload+download) was slower.)
**Do we want this?** 
- There are changes to the deployment/CI infrastructure: Github test matrix
- I have tested the feature as follows using the CI.

Test if matrix over modules are a good thing

---

build.gradle
key.core/build.gradle
key.ui/build.gradle
scripts/jacocokey.gradle

- **Remove deprecated use of $buildDir**
- **fix depracted use of task**
Remove usage of deprecated API from gradle build files
- There are changes to the deployment/CI infrastructure (gradle, github, ...)
- I have tested the feature as follows: build key, rap and docs with gradle successfully; could not test jacoco 

Fix deprecations in build files

---

key.core/src/main/resources/de/uka/ilkd/key/proof/rules/binaryAxioms.key
key.core/src/main/resources/de/uka/ilkd/key/proof/rules/integerAssignment2UpdateRules.key
key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt

- Adds missing taclets for intermediate JavaDL functions `unsignedshiftrightJlong`, `xorJlong`, `orJlong`, and `andJlong`. Without these, one cannot use the Java operators `>>>`, `^`, `|`, and `&` with parameters of type `long`.
- Fixes a bug in the taclets which pull a bitwise negation out of a modality, making them unusable. This was caused by a trivial mismatch between the program variables referenced in the taclets' `\find` and `\replacewith` statements. This bug was not present in 208396f69e.

Translation of bitwise operators

---

key.core/src/main/java/de/uka/ilkd/key/nparser/builder/FunctionPredicateBuilder.java
key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java
key.core/src/main/java/de/uka/ilkd/key/proof/mgt/RuleJustificationInfo.java
key.core/src/test/java/de/uka/ilkd/key/nparser/AdtTests.java
key.ui/examples/standard_key/adt/dt_color.proof
key.ui/examples/standard_key/adt/dt_list_appnil.proof
key.ui/examples/standard_key/adt/dt_list_deconstruct.key
key.ui/examples/standard_key/adt/dt_list_deconstruct.proof
key.ui/examples/standard_key/adt/dt_list_revrev.proof
key.ui/examples/standard_key/adt/dt_nonrec.key

#3662 Parsing problem in \datatypes with no 'self' selectors
Small changes in data type treatment:
- error messaging improved
- consistent naming scheme
- *corrected EQ taclet in correct order (a=b became b=a at one point)*
- *fixed bug in the Axiom taclet for datatypes* which crashed KeY while loading.
- added generated deconstructor rules to "simplify" ruleset 
Small fixes: done.
- There are changes to the taclet rule base [only to taclets created at load time for datatype declarations]
- Pair programming
- I added new test case(s) for new functionality. Manually.
Co-authored by @WolframPfeifer 
The contributions within this …

small fixes to datatype handling
